### ISSUE TITLE
Ломается ватермарк при клике на одну из областей позиций

### ISSUE THREAD

**Issue by KoroljovPavel** [KoroljovPavel/Watermark-Generator-LS-work-3-team-one#31]
После загрузки ватермарка
![Alt text](https://monosnap.com/file/ZSghLqS5t5rchbSQdX1Y8GTFi6fXdv.png)
 кликаем на любую позицию из 9 возможных
 ![Alt text](https://monosnap.com/file/uG3hoPAEtOKxd0Hslv3q30fzMliS84.png)
Затем загружем или новую картинку или новый ватермарк ломается масштабирование
![Alt text](https://monosnap.com/file/TH1gUvkefkZSNpX19lq5sMGGgx4nZw.png)
И выскакивает ошибка из плагина
![Alt text](https://monosnap.com/file/gE6YQMkb7HPG4229Tl4YuZJC5nm0gx.png)

**Comment by pyanulis** [comment]
исправлено в плагине
